### ISSUE TITLE
Интерфейсы без контракта

### ISSUE THREAD

**Issue by k1b24** [alesulkins/ITMO#3]
https://github.com/alesulkins/ITMO/blob/bfd24ac052905abbe8a21b21b7cd63bf07775189/prog/lab3/src/interfaces/ToPay.java#L3

А в чем заключается смысл интерфейсов, которые не описывают никакое поведение? То что они просто есть, не дает никакого нового функционала и никаких возможностей. Если есть интерфейс toPay, то предполагается, что все классы, которые его имплементируют должны иметь возможность что-то оплатить, а значит этот контракт должен быть описан в самом интерфейсе в виде описания метода

**Comment by alesulkins** [comment]
да, согласна, я енам money и интерфейсы еще не доделала, они предполагались у "коротышек"
